### ISSUE TITLE
Shorten review period to 14 days in most cases

### ISSUE THREAD

**Issue by bshannon** [jakartaee/JESP#1]
Now that JESP 1.0 is approved, it's time to start thinking about how to
make it more attractive to MicroProfile!  Let me start...

I know most of you are unhappy with the 30 day minimum review period.
After discussing this with Oracle legal, I have a compromise to propose.

	The default review period is 14 days.  At any time during those
	14 days, any Participant may extend the review period to a total
	of up to 30 days.

Most of the time 14 days will be fine.  In some (hopefully rare) cases,
Oracle (or anyone else) may need more time to (e.g.) evaluate the consequences
of IP lock in for the spec, and would extend the review period.

**Comment by ivargrimstad** [comment]
This is incorporated now.
