### ISSUE TITLE
javax namespace clause seems to need an update

### ISSUE THREAD

**Issue by starksm64** [jakartaee/JESP#3]
The following clause to me reads from to be from the timeframe before there was an understanding that javax could not be modified:

"All development that modifies content in the javax namespace must occur within the scope of a Specification Project operating under the purview of the Jakarta EE Working Group’s Specification Committee and must implement the process as defined by the most recently adopted revision of the JESP.”

As I read this, jakarta is not a package namespace captured under the JESP. I would suggest that the above needs to read something like:

"All development that modifies content in the javax namespace must be moved to a jakarta namespace, and all jakarta namespace development much occur within the scope of a Specification Project operating under the purview of the Jakarta EE Working Group’s Specification Committee and must implement the process as defined by the most recently adopted revision of the JESP.”

**Comment by waynebeaton** [comment]
I'm going to change it instead to:

> All development that modifies content in the javax namespace must be moved to a jakarta namespace. All jakarta namespace development much occur within the scope of a Specification Project operating under the purview of the Jakarta EE Working Group’s Specification Committee and must implement the process as defined by the most recently adopted revision of the JESP.”

**Comment by keilw** [comment]
Why wasn't this ticket closed already, is there something else to do?
